export interface Course {
  id: number;
  icon: string;
  title: string;
  tag: string;
  cat: string;
  color: string;
  desc: string;
  level: string;
  duration: string;
  syllabus: string[];
}

export const courses: Course[] = [
  { id: 1, icon: '🤖', title: 'ChatGPT + Prompting', tag: 'AI Tools', cat: 'ai', color: '#0A9396', desc: 'Master AI conversations. Learn prompt engineering to get better results for writing, research, coding, and more.', level: 'Beginner', duration: '2 Weeks', syllabus: ['Introduction to ChatGPT & OpenAI', 'Understanding how Large Language Models work', 'The Anatomy of a Good Prompt', 'Role-playing & Context Setting', 'Iterating and Refining Responses', 'Using ChatGPT for Writing & Research', 'ChatGPT for Business & Productivity', 'Mini Project: Build Your AI Toolkit'] },
  { id: 2, icon: '✨', title: 'Gemini AI', tag: 'AI Tools', cat: 'ai', color: '#5C67F2', desc: "Harness Google's AI. Use Gemini inside Gmail, Docs, and Sheets to research, write, and automate daily tasks.", level: 'Beginner', duration: '2 Weeks', syllabus: ['What is Gemini AI?', 'Gemini vs ChatGPT: Which to Use When', 'Using Gemini in Gmail', 'Using Gemini in Google Docs', 'Gemini in Google Sheets (formulas)', 'Real-time Research with Gemini', 'Multimodal Input: Images & Text', 'Mini Project: AI Research Report'] },
  { id: 3, icon: '✍️', title: 'Grammarly', tag: 'Productivity', cat: 'productivity', color: '#0EA5E9', desc: 'Write with confidence. Master grammar, tone, clarity, and the AI writing features that make your words shine.', level: 'Beginner', duration: '1 Week', syllabus: ['Installing & Setting Up Grammarly', 'Grammar, Spelling & Punctuation', 'Tone Detection & Adjustment', 'Clarity & Conciseness Improvements', 'Using Grammarly in Gmail & Docs', 'GrammarlyGO AI Features', 'Plagiarism Checker (Premium)', 'Mini Project: Polish a Professional Email'] },
  { id: 4, icon: '🎬', title: 'Loom', tag: 'Productivity', cat: 'productivity', color: '#F97316', desc: 'Record & share video messages. Master async video communication for presentations, demos, and tutorials.', level: 'Beginner', duration: '1 Week', syllabus: ['What is Loom & Why It Matters', 'Installing Loom (Chrome & Desktop)', 'Screen, Camera & Combined Recording', 'Recording Best Practices', 'Editing & Trimming Your Videos', 'Sharing & Permissions', 'Watching Analytics & Engagement', 'Mini Project: Create a Tutorial Video'] },
  { id: 5, icon: '📓', title: 'Notion', tag: 'Productivity', cat: 'productivity', color: '#8B5CF6', desc: 'Build your digital workspace. Organize notes, tasks, wikis, and projects in one beautiful, powerful tool.', level: 'Beginner', duration: '2 Weeks', syllabus: ['Introduction to Notion', 'Pages, Blocks & the Editor', 'Building Databases (Table, Board, Calendar)', 'Templates & Gallery View', 'Filtering, Sorting & Grouping Data', 'Notion AI (Generate & Summarize)', 'Sharing & Collaboration', 'Mini Project: Personal Study Dashboard'] },
  { id: 6, icon: '⚡', title: 'Zapier', tag: 'Automation', cat: 'automation', color: '#EF4444', desc: 'Automate without code. Connect 7000+ apps to eliminate repetitive tasks and run workflows on autopilot.', level: 'Beginner', duration: '2 Weeks', syllabus: ['What is Automation & Why It Matters', 'Zapier Basics: Triggers & Actions', 'Building Your First Zap', 'Multi-Step Zaps', 'Filters & Conditional Logic', 'Zapier Paths & Delay', 'Common Automation Recipes', 'Mini Project: Form-to-Email Automation'] },
  { id: 7, icon: '🔄', title: 'Make (Integromat)', tag: 'Automation', cat: 'automation', color: '#10B981', desc: 'Visual workflow automation. Build powerful multi-step scenarios with data transformation and advanced logic.', level: 'Intermediate', duration: '2 Weeks', syllabus: ['Introduction to Make', 'Modules, Scenarios & Connections', 'Building Your First Scenario', 'Data Mapping & Transformation', 'Routers & Conditional Branching', 'Iterators & Aggregators', 'Scheduling & Error Handling', 'Mini Project: Automated Content Workflow'] },
  { id: 8, icon: '🗄️', title: 'Airtable', tag: 'Productivity', cat: 'productivity', color: '#F59E0B', desc: 'The spreadsheet reimagined. Build powerful databases, track anything, and create custom workflows — no code needed.', level: 'Beginner', duration: '2 Weeks', syllabus: ['Airtable vs Excel: Understanding the Difference', 'Bases, Tables & Fields', 'Field Types & Data Validation', 'Views: Grid, Kanban, Calendar, Gallery', 'Linking Tables & Relational Data', 'Airtable Forms for Data Collection', 'Automations Inside Airtable', 'Mini Project: Event Management Database'] },
  { id: 9, icon: '✅', title: 'ClickUp', tag: 'Productivity', cat: 'productivity', color: '#3B82F6', desc: 'The everything productivity app. Manage tasks, projects, teams, and goals in one fully customizable workspace.', level: 'Beginner', duration: '2 Weeks', syllabus: ['ClickUp Hierarchy: Workspace to Subtasks', 'Creating & Managing Tasks', 'Custom Statuses & Workflows', 'Views: List, Board, Calendar, Gantt', 'Time Tracking & Workload Management', 'ClickUp Docs', 'Automations & Goals', 'Mini Project: Course Progress Tracker'] },
  { id: 10, icon: '🎨', title: 'Canva Pro', tag: 'Design', cat: 'design', color: '#EE9B00', desc: 'Design like a pro. Create stunning visuals for social media, presentations, CVs, flyers, and your personal brand.', level: 'Beginner', duration: '2 Weeks', syllabus: ['Canva Interface & Navigation', 'Working with Templates', 'Typography & Brand Colors', 'Photo Editing & Background Removal', 'Canva Magic AI Tools', 'Brand Kit Setup', 'Magic Resize & Content Planner', 'Mini Project: Personal Brand Kit'] },
];
